### ISSUE TITLE
Safari: activation issues after installation

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#160] opened 2018-11-12 16:35 UTC
soon after installing the latest build 2.1.0.7, I did experience the following:
- info pop-up panel open with the webextension not activated (the red little icon on top of alpheios icon missing)
- double clicking on any words would activate the webextension (again the little red icon would appear on top of Alpheios icon)

in both cases, it could be that the little red icon hasn't been loaded yet.
these scenarios can only be reproducible soon after installing the build, then all works fine.
related to issue #149

**Comment by monzug** [comment] 2018-11-12 16:41
![screen shot 2018-11-12 at 5 40 20 pm](https://user-images.githubusercontent.com/41396793/48361580-19fe8080-e6a2-11e8-91df-df2ac64c03d0.png)

**Comment by kirlat** [comment] 2018-11-14 07:57
@monzug, need your help in reproducing it. I'm testing with the latest version of master now, and I don't see the issue you've described; probably, I'm doing something wrong, but don't know what exactly.

Here is my test sequence:
1. Load an extension. Once loaded, the only option o activate it is either via a menu option ("Alpheios Activate") or through clicking on an Alpheios toolbar icon. In both cases extension activates, and a red icon appears upon its icon.
2. Once activated, I can double click on a word, or open an info panel via a right mouse button menu, and a red icon stays on top of the icon. The only way to make it disappear is to deactivate an extension by clicking on a toolbar icon or via a right mouse button menu.
3. When the extension is deactivated, it can be activated only through the steps listed in step 1. With extension deactivated, double clicking on a word produces no result. It is also impossible to open an into panel.

So I was not able to make either popup or panel to open with Alpheios icon in deactivated state. I'm wondering what would the correct sequence of actions to reproduce that. Thanks!

**Comment by monzug** [comment] 2018-11-14 09:57
@kirlat, I will wait for a new build and try again to see if I can repro
the problem. It could be my test environment on Safari.

**Comment by kirlat** [comment] 2018-11-14 11:56
Thank you, @monzug! Please let me know of the results

**Comment by monzug** [comment] 2018-11-14 13:07
I will. Thanks

**Comment by monzug** [comment] 2018-11-16 10:55
reinstall build 2.1.0.7 and I experience some issues as reported in /alpheios-project/webextension/issues/164.
related to this one, I took a screenshot with tools deactivated but the morphology still working

![screen shot 2018-11-16 at 11 33 16 am](https://user-images.githubusercontent.com/41396793/48617327-76111f80-e996-11e8-8f06-b5398d068a80.png)

the  site is  http://www.thelatinlibrary.com/lucretius/lucretius2.shtml

**Comment by kirlat** [comment] 2018-11-16 11:50
@monzug, is there any particular sentence of steps I can use to reproduce this? Can't achieve this on my macBook at the moment 🙁

**Comment by balmas** [comment] 2018-11-16 12:07
@kirlat I don't think this is necessarily specific to Safari.  As noted in #164 I was seeing very similar behavior using the embedded library on my Ubuntu machine yesterday.  I was using a break point in the inflections component (because that's what I was working on)

**Comment by monzug** [comment] 2018-11-28 14:44
@kirlat, I was able to repro this issue in build 2.1.0.11. When I logged in this afternoon , all the sites in Safari had the tools disabled and the pop-ups still opened (inflection table or look-up or option panel). double clicking on any words did activate the webextension again.

**Comment by balmas** [comment] 2018-11-29 19:36
We are hopeful this might be fixed in build 2.1.0.12

**Comment by monzug** [comment] 2018-11-30 11:40
retest in  Safari build 2.1.012 - confirm what I reported in previous comment related to build 2.1.0.11. the tools are disabled when navigating away from the browser with any pop-ups still opened. when I go back to the tab, the tools are reactivated by using look-up or double-clicking

**Comment by monzug** [comment] 2018-11-30 13:03
FF and Chrome do not have this issue.

**Comment by balmas** [comment] 2018-11-30 13:05
Monica, I don't really understand what you mean by "navigating away from the browser with any pop-ups still opened"

**Comment by monzug** [comment] 2018-11-30 13:15
I have safari, chrome and Firefox. let's say I have two tabs in safari one
with grammar on and an other with look-up. if I go to Chrome or Firefox and
then back to Safari, the tools are not active but pop-ups are still on.

**Comment by balmas** [comment] 2018-11-30 14:18
Ok, that is helpful but I cannot actually reproduce that.  Can you tell me the exact steps you take to switch to Chrome or Firefox from Safari? I have tried using command+tab as well as clicking directly on the chrome and safari icons in the Mac launch bar, and both of those keep the tools activated when I return to Safari.  (NB that I have not yet upgraded to Mojave so we might be running different versions of the Mac OS)

**Comment by monzug** [comment] 2018-11-30 16:17
interesting. I just click directly to the icon in the dock to go from
safari to chrome or firefox. please perform any tasks in the new tab before
going back to safari. all tabs have the tools disabled. Initially I thought
there was a timer... I know this is not possible.

**Comment by balmas** [comment] 2018-11-30 16:53
So, I reproduced this once and now cannot reproduce it again. Actually I produced the following scenarios:

1. Open a page in Safari
2. Activate Alpheios
3. Do a lookup, leave popup open
4. Click on Chrome icon in task bar
5. load a new page in Chome
6. Click on Safari icon in task bar
7. Alpheios popup is still there but tools are deactivated

I reloaded the page in Safari, that reactivated the tools and everything worked fine.
Subsequently I was not able to reproduce steps 1-7.

Then I tried this
1. Open a page in Safari
2. Activate Alpheios
3. Do a lookup, leave popup open
4. Create a new Safari tab
5. Switch back to the original tab, Alpheios is deactivated

But closing browser, and starting over, I can no longer reproduce that scenario either.

**Comment by balmas** [comment] 2018-11-30 17:21
More inconsistency:

1. Open a page in Safari
2. Activate Alpheios
3. Open a new tab
4. Navigate to a new page, leave Alpheios inactive
5. Open a new tab
6. Navigate to a new page, Activate Alpheios
7. Click between tabs, note that each time Alpheios retains the correct activation status, no matter what order you click on the tabs
8. Leave the 1st tab with focus
9. Stop touching the computer
10. Wait a few minutes
11. Click on the 3rd tab. Note that Alpheios icon is no longer activated
12. Click on the 1st tab. Note that Alpheios icon is no longer activated.
13. Use the tools on either page and see that all is well, Alpheios icon shows as reactivated and functionality works.

**Comment by monzug** [comment] 2018-11-30 17:31
there are many inconsistencies, you are right. so there might be a timer
somewhere... anyhow, I do not remember when I have seen these issues. has
it been there from day 1????

**Comment by balmas** [comment] 2018-11-30 17:37
quite possibly. Or it's possible that they have become more apparent as the application becomes overall more stable.

**Comment by balmas** [comment] 2018-12-07 21:35
please test in build 2.1.0.14

**Comment by monzug** [comment] 2018-12-09 09:51
Cannot repro the issues described above in build 2.1.0.14, e.g. switching browser from Safari to Chrome or  opening new tabs.
However I was able to reproduce the above issues once with computer in sleep mode and after leaving the tools on overnite.
Glad to see that tools stay in activate state when browsing through browsers. Pass it to @balmas to confirm that this is good enough for the release.

**Comment by kirlat** [comment] 2018-12-10 04:51
I'm not sure there is any way to prevent Safari app extension deactivation after mac going to sleep. Probably we do not have any options here at all 🙁.

**Comment by balmas** [comment] 2018-12-10 12:34
I think it's good enough for release. We should enter a separate issue for reactivation upon sleep state, just so that we can remember to come back to it post-release and investigate further with Apple if necessary. @monzug can you do that and then close this one? Thanks!

**Closed** 2018-12-10 12:44 UTC
Labels: bug, safari
