### ISSUE TITLE
background script errors in console/activation issue

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#292] opened 2020-05-28 19:45 UTC
I'm not sure if these are related but I have been noticing the following:

1) when you open a new browser window or tab and the first thing you is try to activate Alpheios, it takes two clicks on the alpheios icon to activate it. The first one does nothing.

2) there are a ton of background script errors appearing in the background debug window

![Screenshot from 2020-05-28 15-43-13](https://user-images.githubusercontent.com/644870/83186273-464de680-a0fa-11ea-825e-06c385feea90.png)

**Comment by balmas** [comment] 2020-05-28 19:46
I have seen the activation behavior in both Chrome and Firefox.

@kirlat could you investigate?

**Comment by kirlat** [comment] 2020-05-29 11:22
I can't reproduce it in Chrome (there are some errors in the console there, but they do not require a second click to activate an extension) but I see something very similar in FF. Will investigate.

**Comment by kirlat** [comment] 2020-06-02 17:12
Changes that would hopefully fix the issue has been merged into master.

**Closed** 2020-06-02 17:44 UTC
Labels: bug, waiting_verification

**Comment by balmas** [comment] 2020-06-04 20:36
these errors aren't occurring anymore in  Alpheios Reading Tools 3.1.0 build qa.20200602407  and the activation problem seems resolved.

@monzug can you just confirm that you don't have any problems activating the extension after installation or changing pages in both Chrome and FF?

**Comment by monzug** [comment] 2020-06-05 14:08
I have seen this problem in previous builds but not in the latest. I think we had this issue before, it sounds familiar.
