### ISSUE TITLE
FF: after sign in, pop-up loads for ever

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#288] opened 2020-05-08 12:59 UTC
related to issue https://github.com/alpheios-project/webextension/issues/283
release version on FF 74.0 (64-bit) on PC and Mac
When I sign in with apple or with google or as an existing user, the next popup keeps loading for ever so I close it, I go back to log in, click on the log in button and I am logged in.  when I sign in with Apple, after prompting for id/psw, I have to click on Continue. I can keep clicking but it does not do anything, but then when I go back to the Alpheios and click on log in, I am logged in.
see screenshots 
![login-apple-ff](https://user-images.githubusercontent.com/41396793/81407888-2bdfa900-910a-11ea-8f7a-b93f24ee5ba7.JPG)
![login-ff](https://user-images.githubusercontent.com/41396793/81407891-2d10d600-910a-11ea-9474-e00dda2f45d3.JPG)

**Comment by balmas** [comment] 2020-05-08 13:02
@kirlat can you please investigate this ? Thank you.

**Comment by kirlat** [comment] 2020-05-08 14:09
I've tested it on macOS 10.15.4 in FF 76.0 and I cannot confirm this so far. I do see the first screen, and when I click on "Continue", it closes it (it seems this is shown in a full-size popup window) and brings me to the user tab in an Alpheios panel, a status is shown as "logged in".

I don't know if it's important or not, but before this screen I was:
1. Shown a 6-digit confirmation code that was displayed on my mac and that I've entered into the browser.
2. Displayed a notification that I signed in from a new device and whether I want to trust it or not. I've chosen to trust it.

**Comment by kirlat** [comment] 2020-05-08 14:23
I did a couple of other tests on mac and it is working as expected for me. Will check it on PC.

>  when I sign in with Apple, after prompting for id/psw, I have to click on Continue. I can keep clicking but it does not do anything, but then when I go back to the Alpheios and click on log in, I am logged in.

The windows on a first screenshot seems to be a full-size popup windows that opens on top the one with the panel. It seems that this window fails to close for whatever reason and a JS function fails to return a value that will indicate a completed authentication.

@monzug, since it is a FF window, could you please press fn+F12 to open dev tools, select the console tab and see if there are any suspicious messages there? Are there any messages appearing when you press a "continue" button? Are there any blocker plugins in FF (or any plugins at all) active that may prevent this window from closing?

**Comment by kirlat** [comment] 2020-05-08 14:43
Was able to sign in with Apple ID from PC on Win10 in FF 77.0b3 (this is a developer edition). The window on a screenshot closes slowly, but it closes finally. 

I've also logged in with my Gmail account without any problem whatsoever.

**Comment by monzug** [comment] 2020-05-08 14:51
No error message on console. I have to say that I have a very slow
connection but I did my login testing with the 3 browsers on PC/Mac and I
had this problem only on FF. I am glad you don't see any issue,

**Comment by balmas** [comment] 2020-05-08 15:43
I can't reproduce this one either. I think it may be a problem with FF and is likely related to the slow connection so there are two separate questions here:

It sounds as if it is timing out on the redirect back from the authentication, after the authentication is successful. This is probably why after refresh the user is logged in. It's possible that Firefox handles this timeout differently than Chrome.

So there are 2 separate questions

1) can we increase a timeout setting to be more forgiving to prevent this from happening?
2) is there any relationship to the Auth0 upgrade

I'm pretty dubious that the latter is true, but it would be good to confirm that. The best way is probably to have @monzug test at a time that I can set login form back quickly to the earlier version, so that we can see if she can reproduce with only the later version.

@monzug let's setup a time to do this on Monday?

**Comment by monzug** [comment] 2020-05-08 16:57
I will have a faster connection by then!!! let's see.

**Comment by balmas** [comment] 2020-05-11 15:02
@monzug reports that this is solved by upgrading to FF76. We need to note this in the FAQ.

**Closed by balmas** 2020-05-11 15:02 UTC
Labels: firefox
