### ISSUE TITLE
Safari: the content of Define needs restyling

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#136] opened 2018-10-29 16:17 UTC
in poeasialatina, the content of define is all messed up

![screen shot 2018-10-29 at 5 05 49 pm](https://user-images.githubusercontent.com/41396793/47663722-da15a480-db9d-11e8-8134-a3ea75a5cbd1.png)

**Comment by balmas** [comment] 2018-10-29 17:20
The site is http://www.poesialatina.it/

**Comment by balmas** [comment] 2018-10-29 17:20
assigning to @irina060981 to investigate

**Comment by irina060981** [comment] 2018-10-30 10:30
I have checked - the problem is very strange - this site has its own bootstrap styles applied in the head.
And in firefox, chrome webextension has normarl priority and all style's weight applying in a normal way.
But as for Safari - for some case Safari app extension styles has lower priority. So Bootstrap normalizing styles kills our styles (for example for buttons).
I will search for more details about it.

**Comment by monzug** [comment] 2018-11-05 18:17
an other example of style

![screen shot 2018-11-05 at 6 59 14 pm](https://user-images.githubusercontent.com/41396793/48017771-7821e580-e12f-11e8-9394-d5bceb2b9ea3.png)

**Comment by irina060981** [comment] 2018-11-17 12:49
Solved upon https://github.com/alpheios-project/webextension/issues/135
Fixed styles

**Comment by irina060981** [comment] 2018-11-19 14:14
Merged and closed

**Closed by irina060981** 2018-11-19 14:14 UTC
Labels: safari

**Comment by balmas** [comment] 2018-11-19 15:03
ready for testing in build 2.1.0.9

**Comment by monzug** [comment] 2018-11-19 16:36
the define looks great in 2.1.0.9 however i can't check the inflection table as they are all messed up. will wait for fix 135

**Comment by irina060981** [comment] 2018-11-20 13:16
I have fixed it upon https://github.com/alpheios-project/webextension/issues/135
https://github.com/alpheios-project/components/pull/285

**Comment by monzug** [comment] 2018-11-21 15:10
safari 2.1.0.10, verified
